name: Darling CI

on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        git remote set-url origin https://github.com/darlinghq/darling.git
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install devscripts equivs
        sudo mk-build-deps -ir
    - name: Build DEB
      run: tools/makedeb
    - name: Move DEBs
      run: mkdir dist && mv ../*.deb dist
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: 'debs'
        path: dist/

  build-dsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        git remote set-url origin https://github.com/darlinghq/darling.git
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install devscripts dpkg-dev
    - name: Build DSC
      run: tools/makedeb --dsc
    - name: Move DSCs
      run: mkdir source && mv ../*~testing.* source
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: 'source'
        path: source/
